# Generated by Django 2.2.24 on 2023-05-19 02:42

from django.db import migrations


def fill_up_new_building(apps, schema_editor):
    flat = apps.get_model('property', 'Flat')
    flat.objects.filter(construction_date__gte=2015).update(new_building=True)
    flat.objects.filter(construction_date__lte=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
    ]
