# Generated by Django 2.2.24 on 2023-05-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Новое ли здание'),
        ),
    ]
