# Generated by Django 2.2.24 on 2023-05-19 19:04

from django.db import migrations


def fill_up_new_building(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    flats.objects.filter(construction_year__gte=2015).update(new_building=True)
    flats.objects.filter(construction_year__lte=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [migrations.RunPython(fill_up_new_building)]
