# Generated by Django 2.2.24 on 2023-05-19 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes_flat', to=settings.AUTH_USER_MODEL, verbose_name='кто лайкнул'),
        ),
    ]
