# Generated by Django 2.2.24 on 2023-05-19 19:21

from django.db import migrations
import phonenumbers


def normalize_owner_phone(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    for flat in flats.objects.all().iterator():
        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_phone):
            flat.owner_pure_phone = parsed_phone
            flat.save()


def move_backward(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    for flat in flats.objects.all().iterator():
        flat.owner_pure_phone.delete()
        flat.update()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_owner_pure_phone'),
    ]

    operations = [migrations.RunPython(normalize_owner_phone)
    ]
