# Generated by Django 2.2.24 on 2023-05-11 19:33

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    for flat in Flats.objects.all():
        parsed_phones = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if not phonenumbers.is_valid_number(parsed_phones):
            continue
        flat.owner_pure_phone = phonenumbers.format_number(
            parsed_phones, phonenumbers.PhoneNumberFormat.E164)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [migrations.RunPython(fill_owner_pure_phone)
    ]
