# Generated by Django 2.2.24 on 2023-05-12 18:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230511_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region='RU', verbose_name='Нормализованный номер владельца')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_owner', to='property.Flat', verbose_name='ФИО владельца')),
                ('owned_flat', models.ManyToManyField(db_index=True, related_name='owned_flat', to='property.Flat', verbose_name='квартиры в собственности')),
            ],
        ),
    ]
