# Generated by Django 2.2.24 on 2023-05-19 20:00

from django.db import migrations


def link_flat_with_owner(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    owners = apps.get_model('property', 'Owner')
    for owner in owners.objects.all().iterator():
        owner.flat.set(flats.objects.filter(owner=owner.name))


def move_backward(apps, schema_editor):
    owners = apps.get_model('property', 'Owner')
    owners.objects.prefetch_related('flat').remove()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230519_2246'), ]

    operations = [migrations.RunPython(link_flat_with_owner, move_backward)]
