# Generated by Django 2.2.24 on 2023-05-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
