# Generated by Django 2.2.24 on 2023-05-12 20:13

from django.db import migrations


def migrate_data_to_owner_model(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    Owners = apps.get_model('property', 'Owner')
    for flat in Flats.objects.all():
        Owners.objects.get_or_create(
            name=flat.owner,
            owner_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone)


def move_backward(apps, shema_editor):
    Flats = apps.get_model('property', 'Flat')
    Owners = apps.get_model('property', 'Owner')
    Owner = Owners.objects.all()
    for flat in Flats.objects.all():
        Owner.filter(
            name=flat.owner,
            owner_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230512_2157'),
    ]

    operations = [migrations.RunPython(
        migrate_data_to_owner_model,
        move_backward)
        ]
