# Generated by Django 2.2.24 on 2023-05-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    def link_owned_flats_with_flats(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        for owner in Owner.objects.all():
            owner.owned_flat.set(
                Flat.objects.filter(owner=owner.name))

    def move_backward(apps, schema_editor):
        Owner = apps.get_model('property', 'Owner')
        for owner in Owner.objects.all():
            owner.owned_flat.clear()

    dependencies = [
        ('property', '0012_auto_20230513_0003'),
    ]

    operations = [migrations.RunPython(
        link_owned_flats_with_flats,
        move_backward)
    ]
