# Generated by Django 3.2.10 on 2023-05-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230516_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_flat',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
